import { useEffect, useRef, useState } from 'react';
import { Activity, AlertTriangle, ArrowDownRight, ArrowRight, Bell, CalendarDays, CheckCircle2, ChevronDown, CircleHelp, CloudSun, Coins, Download, Droplets, FileText, Home, Leaf, Map, MapPin, Menu, Plane, Plus, Search, Settings, ShieldCheck, UploadCloud, Waves, X } from 'lucide-react';
import { Area, AreaChart, CartesianGrid, ResponsiveContainer, Tooltip, XAxis, YAxis } from 'recharts';

type Status = 'Optimal' | 'Insufficient' | 'Excess water';
type Field = { id:number; name:string; block:string; crop:string; area:number; water:number; status:Status; location:string; action:string; x:number; y:number; shape:string; };
type Issue = {id:number; fieldId:number; label:string; severity:'High'|'Medium'; time:string; resolved:boolean; note:string};
type Page = 'Dashboard'|'My Fields'|'Drone Scans'|'Alerts'|'Reports'|'Settings';
const initialFields:Field[] = [
{id:1,name:'Field 1',block:'North Block',crop:'Maize',area:2.5,water:5200,status:'Optimal',location:'Section A',action:'Continue monitoring.',x:24,y:31,shape:'16,14 40,12 43,42 20,45'},
{id:2,name:'Field 2',block:'West Block',crop:'Beans',area:1.8,water:4100,status:'Insufficient',location:'Section C',action:'Inspect irrigation coverage and check soil moisture.',x:31,y:66,shape:'19,48 44,44 49,75 24,81'},
{id:3,name:'Field 3',block:'South Block',crop:'Maize',area:3.2,water:6800,status:'Excess water',location:'Section B',action:'Inspect irrigation pipes and nearby sprinklers.',x:64,y:34,shape:'44,12 75,16 82,53 49,66'},
{id:4,name:'Field 4',block:'East Block',crop:'Tomatoes',area:2.1,water:2400,status:'Optimal',location:'Section D',action:'Continue monitoring.',x:69,y:76,shape:'50,70 84,55 88,85 56,94'}
];
const initialIssues:Issue[] = [
{id:1,fieldId:3,label:'Possible water leakage',severity:'High',time:'08:45',resolved:false,note:''},
{id:2,fieldId:2,label:'Possible insufficient watering',severity:'Medium',time:'07:20',resolved:false,note:''},
{id:3,fieldId:3,label:'Follow-up inspection required',severity:'Medium',time:'Yesterday',resolved:false,note:''}
];
const trends = [{day:'Mon',litres:5100},{day:'Tue',litres:6300},{day:'Wed',litres:7800},{day:'Thu',litres:6500},{day:'Fri',litres:7100},{day:'Sat',litres:8300},{day:'Sun',litres:6900}];
const fmt = (n:number)=>new Intl.NumberFormat('en-ZA').format(n);
const load = <T,>(key:string,fallback:T):T=>{try {const value=localStorage.getItem(key);return value?JSON.parse(value) as T:fallback;}catch{return fallback;}};
function App(){
 const [page,setPage]=useState<Page>('Dashboard');
 const [fields,setFields]=useState<Field[]>(()=>load('aqua_fields',initialFields));
 const [issues,setIssues]=useState<Issue[]>(()=>load('aqua_issues',initialIssues));
 const [selected,setSelected]=useState(3);
 const [upload,setUpload]=useState<string|null>(null);
 const [uploadName,setUploadName]=useState('');
 const [scanTime,setScanTime]=useState('7 Oct 2026, 08:30');
 const [scans,setScans]=useState<string[]>(()=>load('aqua_scans',['7 Oct 2026, 08:30 — Example drone scan']));
 const [modal,setModal]=useState<'inspection'|'scan'|'help'|null>(null);
 const [note,setNote]=useState('');
 const [toast,setToast]=useState('');
 const [mobile,setMobile]=useState(false);
 const [period,setPeriod]=useState('This week');
 const [farmName,setFarmName]=useState(()=>load('aqua_farm','Shirly’s Farm'));
 const [waterRate,setWaterRate]=useState(()=>load('aqua_rate',0.015));
 const fileInput=useRef<HTMLInputElement>(null);
 useEffect(()=>{localStorage.setItem('aqua_fields',JSON.stringify(fields));},[fields]);
 useEffect(()=>{localStorage.setItem('aqua_issues',JSON.stringify(issues));},[issues]);
 useEffect(()=>{localStorage.setItem('aqua_scans',JSON.stringify(scans));},[scans]);
 useEffect(()=>{localStorage.setItem('aqua_farm',JSON.stringify(farmName));localStorage.setItem('aqua_rate',JSON.stringify(waterRate));},[farmName,waterRate]);
 const show=(message:string)=>{setToast(message);window.setTimeout(()=>setToast(''),3800);};
 const total=fields.reduce((sum,f)=>sum+f.water,0);
 const active=issues.filter(i=>!i.resolved);
 const affected=[...new Set(active.map(i=>i.fieldId))].length;
 const chosen=fields.find(f=>f.id===selected)!;
 const choose=(id:number)=>{setSelected(id);setPage('Dashboard');setMobile(false);};
 const navigate=(target:Page)=>{setPage(target);setMobile(false);};
 const importImage=(file?:File)=>{if(!file)return;if(!file.type.startsWith('image/')){show('Please select an image file.');return;}if(file.size>12*1024*1024){show('Image must be under 12 MB.');return;}const reader=new FileReader();reader.onload=()=>{setUpload(String(reader.result));setUploadName(file.name);const stamp=new Date().toLocaleString('en-ZA');setScanTime(stamp);setScans(old=>[`${stamp} — ${file.name}`,...old]);setPage('Dashboard');show('Image uploaded. Demo overlays shown; no AI analysis was performed.');};reader.readAsDataURL(file);};
 const markInspection=()=>{const issue=active.find(i=>i.fieldId===selected);if(!issue){show('No open issue for this field.');return;}setNote(issue.note);setModal('inspection');};
 const resolve=()=>{setIssues(old=>old.map(i=>i.fieldId===selected&&!i.resolved?{...i,resolved:true,note:note.trim()}:i));setFields(old=>old.map(f=>f.id===selected?{...f,status:'Optimal'}:f));setModal(null);show('Inspection recorded. Await a new scan to verify the field condition.');};
 const downloadReport=()=>{const lines=[['Field','Crop','Area (ha)','Water (L)','Status'],...fields.map(f=>[f.name,f.crop,String(f.area),String(f.water),f.status])].map(r=>r.map(s=>'"'+s.replaceAll('"','""')+'"').join(','));const blob=new Blob([lines.join('\n')],{type:'text/csv'});const url=URL.createObjectURL(blob);const a=document.createElement('a');a.href=url;a.download='aquasmart-field-report.csv';a.click();URL.revokeObjectURL(url);show('CSV report downloaded.');};
 const navigation:[Page,typeof Home][]=[['Dashboard',Home],['My Fields',Map],['Drone Scans',Plane],['Alerts',Bell],['Reports',FileText],['Settings',Settings]];
 return <div className="app">
 <aside className={`sidebar ${mobile?'open':''}`}>
 <div className="brand"><span className="brand-mark"><Droplets size={27}/></span><div><strong>AquaSmart</strong><small>Drone AI. Less water. Better farms.</small></div></div>
 <nav>{navigation.map(([label,Icon])=><button key={label} className={`nav-link ${page===label?'active':''}`} onClick={()=>navigate(label)}><Icon size={19}/><span>{label}</span>{label==='Alerts'&&active.length>0&&<em>{active.length}</em>}</button>)}</nav>
 <div className="sidebar-bottom"><div className="farmer-avatar">SM</div><div><strong>Shirly Mokoena</strong><small>Small-scale farmer</small></div></div>
 </aside>
 {mobile&&<button className="mobile-backdrop" onClick={()=>setMobile(false)} aria-label="Close menu"/>}
 <main className="main">
 <header className="topbar"><div className="top-left"><button className="icon-button menu-toggle" onClick={()=>setMobile(true)} aria-label="Open menu"><Menu size={22}/></button><div><h1>{page==='Dashboard'?'Good morning, Shirly!':page} {page==='Dashboard'&&<span className="sun">☀</span>}</h1><p>{page==='Dashboard'?"Here's your farm's irrigation overview.":page==='Drone Scans'?'Upload and review drone imagery.':page==='Settings'?'Update your farm preferences.':'Monitor your farm with ease.'}</p></div></div><div className="top-meta"><span><CalendarDays size={18}/><span>Latest scan<br/><b>{scanTime}</b></span></span><span><MapPin size={18}/><span>Polokwane, Limpopo</span></span><span><CloudSun size={27}/><span><b>24°C</b><br/>Demo weather</span></span></div></header>
 <div className="demo-notice"><CircleHelp size={15}/> Demo mode: field values, overlays, alerts and weather are illustrative. Image uploads do not run AI detection.</div>
 {page==='Dashboard'&&<>
 <section className="kpis"><Kpi icon={<Droplets/>} tone="blue" title="Total Water Usage" value={`${fmt(total)} L`} detail={period}/><Kpi icon={<Coins/>} tone="gold" title="Estimated Water Cost" value={`R${fmt(Math.round(total*waterRate))}`} detail={`Example rate: R${waterRate}/L`}/><Kpi icon={<AlertTriangle/>} tone="red" title="Detected Problem Areas" value={String(affected)} detail="Need inspection" onClick={()=>navigate('Alerts')}/><Kpi icon={<Leaf/>} tone="green" title="Overall Field Status" value={affected?'Needs attention':'Good'} detail={`${fields.length-affected} fields without open alerts`}/></section>
 <section className="primary-grid"><div className="panel map-panel"><div className="panel-head"><h2>Farm Heatmap <span className="muted">(Latest Drone Scan)</span></h2><button className="text-link" onClick={()=>setModal('scan')}><UploadCloud size={16}/> Upload scan</button></div><FarmMap upload={upload} fields={fields} selected={selected} onSelect={setSelected}/><div className="map-footer"><span><span className="dot green"/> No visible issue</span><span><span className="dot yellow"/> Check water coverage</span><span><span className="dot red"/> Suspected excess water</span></div></div>
 <div className="panel details-panel"><div className="panel-head"><h2>{chosen.name} — {chosen.block}</h2><span className={`pill ${chosen.status==='Optimal'?'ok':chosen.status==='Excess water'?'danger':'warn'}`}>{chosen.status}</span></div><div className="detail-visual"><FarmMap upload={upload} fields={fields} selected={selected} onSelect={setSelected} mini/></div><div className="detail-lines"><div><MapPin size={16}/><span>Location</span><b>{chosen.location}</b></div><div><CalendarDays size={16}/><span>Detection date</span><b>{scanTime}</b></div><div><Activity size={16}/><span>AI assessment</span><b>{chosen.status==='Optimal'?'No visible issue in demo':chosen.status==='Excess water'?'Possible overwatering or leakage':'Possible insufficient watering'}</b></div><div><ShieldCheck size={16}/><span>Recommended action</span><b>{chosen.action}</b></div></div><button className="primary-button" onClick={markInspection}><CheckCircle2 size={17}/> Mark for Inspection <ArrowRight size={17}/></button></div></section>
 <section className="lower-grid"><div className="panel"><div className="panel-head"><h2>Field Overview</h2><button className="text-link" onClick={()=>navigate('My Fields')}>View all</button></div><FieldTable fields={fields} onSelect={choose}/></div><div className="panel"><div className="panel-head"><h2>Water Usage Trend</h2><select value={period} onChange={e=>setPeriod(e.target.value)}><option>This week</option><option>Demo week</option></select></div><UsageChart/></div><div className="panel"><div className="panel-head"><h2>Recent Alerts</h2><button className="text-link" onClick={()=>navigate('Alerts')}>View all</button></div><AlertList issues={issues.slice(0,4)} fields={fields} onSelect={choose}/></div></section>
 </>}
 {page==='My Fields'&&<section className="panel full-panel"><div className="panel-head"><h2>Registered Fields</h2><span className="muted">{fields.length} fields · {fields.reduce((n,f)=>n+f.area,0).toFixed(1)} ha</span></div><FieldTable fields={fields} onSelect={choose}/><div className="hint">Select View to open the field's location, heatmap and recommended action on the dashboard.</div></section>}
 {page==='Drone Scans'&&<section className="two-col"><div className="panel full-panel"><h2>Upload Drone Image</h2><p className="muted">Upload a JPG, PNG or WebP image to preview it on the farm dashboard. The heatmap overlays remain example data.</p><div className="upload-zone" onClick={()=>fileInput.current?.click()}><UploadCloud size={40}/><strong>Choose a drone image</strong><span>JPG, PNG, WebP · Max 12 MB</span><button className="primary-button small" type="button">Browse files</button></div>{uploadName&&<p className="hint">Latest uploaded image: {uploadName}</p>}<button className="outline-button" onClick={()=>{setUpload(null);setUploadName('');show('Restored example farm image.');}}>Restore example image</button></div><div className="panel full-panel"><h2>Scan History</h2><div className="scan-list">{scans.map((scan,i)=><div key={i}><Plane size={18}/><span>{scan}</span><span className="pill ok">{i===0?'Latest':'Saved'}</span></div>)}</div><div className="hint">Real drone integration and AI inference require a backend and trained detection model.</div></div></section>}
 {page==='Alerts'&&<section className="panel full-panel"><div className="panel-head"><h2>Detected Problem Areas</h2><span className="pill danger">{active.length} open alerts</span></div><AlertList issues={issues} fields={fields} onSelect={choose} expanded/><div className="hint">All alerts are simulated. Inspect the actual field before making changes to irrigation.</div></section>}
 {page==='Reports'&&<section className="two-col"><div className="panel full-panel"><div className="panel-head"><h2>Water Usage</h2><button className="outline-button" onClick={downloadReport}><Download size={16}/> Export CSV</button></div><UsageChart/><p className="hint">Illustrative usage trend, not readings from water meters.</p></div><div className="panel full-panel"><h2>Farm Summary</h2><div className="report-row"><span>Total example water usage</span><strong>{fmt(total)} L</strong></div><div className="report-row"><span>Estimated water cost</span><strong>R{fmt(Math.round(total*waterRate))}</strong></div><div className="report-row"><span>Fields requiring inspection</span><strong>{affected}</strong></div><div className="report-row"><span>Recorded inspections</span><strong>{issues.filter(i=>i.resolved).length}</strong></div><button className="primary-button" onClick={downloadReport}><Download size={17}/> Download Field Report</button></div></section>}
 {page==='Settings'&&<section className="panel settings-panel"><h2>Farm Preferences</h2><label>Farm name<input value={farmName} onChange={e=>setFarmName(e.target.value)} maxLength={80}/></label><label>Estimated water price (R per litre)<input type="number" min="0" step="0.001" value={waterRate} onChange={e=>setWaterRate(Math.max(0,Number(e.target.value)||0))}/></label><p className="hint">Your preferences and inspection notes are saved in this browser only. No account or cloud storage is connected.</p><button className="primary-button" onClick={()=>show('Farm preferences saved locally.')}>Save Preferences</button><button className="outline-button" onClick={()=>setModal('help')}><CircleHelp size={16}/> About this prototype</button></section>}
 </main>
 <input ref={fileInput} type="file" accept="image/png,image/jpeg,image/webp" hidden onChange={e=>{importImage(e.target.files?.[0]);e.target.value='';}}/>
 {modal&&<div className="modal-backdrop" onClick={()=>setModal(null)}><div className="modal" onClick={e=>e.stopPropagation()}><button className="close" onClick={()=>setModal(null)} aria-label="Close"><X size={20}/></button>{modal==='inspection'?<><h2>Record Field Inspection</h2><p className="muted">{chosen.name} · {chosen.location} · {chosen.status}</p><label>What did you find?<textarea placeholder="e.g. Found a loose irrigation pipe. Repaired it and will rescan tomorrow." value={note} onChange={e=>setNote(e.target.value)} rows={4}/></label><p className="hint">Marking an issue inspected does not verify the next scan. A follow-up flight is recommended.</p><button className="primary-button" onClick={resolve} disabled={!note.trim()}>Save Inspection & Close Alerts</button></>:modal==='scan'?<><h2>New Drone Scan</h2><p>Upload a drone photo to preview it on the farm dashboard.</p><p className="hint">Automated drone flight scheduling is not connected in this prototype.</p><button className="primary-button" onClick={()=>{setModal(null);fileInput.current?.click();}}><UploadCloud size={17}/> Upload Image</button></>:<><h2>About AquaSmart MVP</h2><p>This is a working interactive frontend prototype with example data. It does not include actual drone control, georeferenced image analysis, AI inference, water meter integration, or weather feeds.</p><p>To make real detections, connect the image upload to a FastAPI backend and a trained, validated computer vision model.</p></>}</div></div>}
 {toast&&<div className="toast"><CheckCircle2 size={17}/>{toast}</div>}
 </div>;
}
function Kpi({icon,tone,title,value,detail,onClick}:{icon:React.ReactNode;tone:string;title:string;value:string;detail:string;onClick?:()=>void}){return <div className={`kpi ${onClick?'clickable':''}`} onClick={onClick} role={onClick?'button':undefined} tabIndex={onClick?0:undefined} onKeyDown={e=>{if(onClick&&(e.key==='Enter'||e.key===' '))onClick();}}><span className={`kpi-icon ${tone}`}>{icon}</span><div><p>{title}</p><strong>{value}</strong><small>{detail}</small></div><div className={`spark ${tone}`}><svg viewBox="0 0 110 28" preserveAspectRatio="none"><path d="M0 24 C15 19 18 8 33 17 S55 23 69 12 S88 22 110 4" fill="none" stroke="currentColor" strokeWidth="2"/></svg></div></div>}
function FarmMap({upload,fields,selected,onSelect,mini=false}:{upload:string|null;fields:Field[];selected:number;onSelect:(id:number)=>void;mini?:boolean}){return <div className={`farm-map ${mini?'mini':''}`} style={upload?{backgroundImage:`linear-gradient(0deg,rgba(8,42,26,.12),rgba(8,42,26,.12)),url("${upload}")`}:undefined}><svg viewBox="0 0 100 100" preserveAspectRatio="none" className="map-svg" role="img" aria-label="Illustrative farm field heatmap"><defs><filter id="blur"><feGaussianBlur stdDeviation="2.2"/></filter></defs>{fields.map(f=><g key={f.id} onClick={()=>onSelect(f.id)} className="field-zone" tabIndex={0} role="button" aria-label={`Select ${f.name}`} onKeyDown={e=>{if(e.key==='Enter')onSelect(f.id);}}><polygon points={f.shape} fill={f.status==='Optimal'?'#25bf6b':f.status==='Excess water'?'#ef493b':'#f8c840'} fillOpacity={selected===f.id?.48:.28} stroke={f.status==='Optimal'?'#34e18a':f.status==='Excess water'?'#ff6556':'#ffe27b'} strokeWidth={selected===f.id?.85:.42} vectorEffect="non-scaling-stroke"/><text x={f.x} y={f.y} className="map-label" textAnchor="middle">{mini?'':f.name}</text></g>)}<ellipse cx="71" cy="30" rx="6" ry="9" fill="#ee1c1c" opacity=".65" filter="url(#blur)"/>{selected===3&&<circle cx="71" cy="30" r="1.7" fill="#fff" stroke="#d52525" strokeWidth=".5"/>}</svg>{!mini&&<div className="map-label-overlay">Illustrative field boundaries · not georeferenced</div>}</div>}
function FieldTable({fields,onSelect}:{fields:Field[];onSelect:(id:number)=>void}){return <div className="table-scroll"><table><thead><tr><th>Field</th><th>Crop</th><th>Area</th><th>Water Usage</th><th>Status</th><th>Action</th></tr></thead><tbody>{fields.map(f=><tr key={f.id}><td><strong>{f.name}</strong></td><td>{f.crop}</td><td>{f.area} ha</td><td>{fmt(f.water)} L</td><td><span className={`pill ${f.status==='Optimal'?'ok':f.status==='Excess water'?'danger':'warn'}`}>{f.status}</span></td><td><button className="text-link" onClick={()=>onSelect(f.id)}>View <ArrowRight size={14}/></button></td></tr>)}</tbody></table></div>}
function UsageChart(){return <div className="chart"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trends} margin={{top:12,right:12,left:-18,bottom:0}}><defs><linearGradient id="usageFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#3c9bff" stopOpacity={.25}/><stop offset="100%" stopColor="#3c9bff" stopOpacity={.01}/></linearGradient></defs><CartesianGrid vertical={false} stroke="#e8edf3"/><XAxis dataKey="day" tickLine={false} axisLine={false} tick={{fill:'#6a7890',fontSize:11}}/><YAxis tickLine={false} axisLine={false} tick={{fill:'#6a7890',fontSize:11}} tickFormatter={n=>`${n/1000}k`}/><Tooltip formatter={v=>`${fmt(Number(v))} L`}/><Area type="monotone" dataKey="litres" stroke="#2586ff" strokeWidth={2.5} fill="url(#usageFill)" dot={{r:3,fill:'#2586ff',stroke:'#fff',strokeWidth:1.5}}/></AreaChart></ResponsiveContainer></div>}
function AlertList({issues,fields,onSelect,expanded=false}:{issues:Issue[];fields:Field[];onSelect:(id:number)=>void;expanded?:boolean}){return <div className="alerts">{issues.length===0&&<p className="muted">No alerts.</p>}{issues.map(i=><button className="alert-row" key={i.id} onClick={()=>onSelect(i.fieldId)}><span className={`alert-icon ${i.resolved?'green':i.severity==='High'?'red':'yellow'}`}>{i.resolved?<CheckCircle2 size={19}/>:i.severity==='High'?<AlertTriangle size={19}/>:<Waves size={19}/>}</span><span className="alert-content"><strong>{i.label}</strong><small>{fields.find(f=>f.id===i.fieldId)?.name} · {i.resolved?'Inspected':i.severity+' priority'}</small>{expanded&&<small>{i.note||'Select to view location and recommendation.'}</small>}</span><span className="alert-time">{i.time}</span><ArrowRight size={16}/></button>)}</div>}
export default App;
